[project]
name = "autonomous-vehicle-nav"
authors = ["Your Name"]
description = "AI-powered autonomous vehicle navigation system on Stacks blockchain"
telemetry = false
requirements = []
boot_contracts = []

[contracts.vehicle-registry]
path = "contracts/vehicle-registry.clar"
clarity_version = 2
epoch = 2.1

[contracts.route-validation]
path = "contracts/route-validation.clar"
clarity_version = 2
epoch = 2.1

[contracts.autonomous-nav]
path = "contracts/autonomous-nav.clar"
clarity_version = 2
epoch = 2.1

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
